# 초성 리스트. 00 ~ 18
CHOSUNG_LIST = [
    "ㄱ",
    "ㄲ",
    "ㄴ",
    "ㄷ",
    "ㄸ",
    "ㄹ",
    "ㅁ",
    "ㅂ",
    "ㅃ",
    "ㅅ",
    "ㅆ",
    "ㅇ",
    "ㅈ",
    "ㅉ",
    "ㅊ",
    "ㅋ",
    "ㅌ",
    "ㅍ",
    "ㅎ",
]
# 중성 리스트. 00 ~ 20
JUNGSUNG_LIST = [
    "ㅏ",
    "ㅐ",
    "ㅑ",
    "ㅒ",
    "ㅓ",
    "ㅔ",
    "ㅕ",
    "ㅖ",
    "ㅗ",
    "ㅘ",
    "ㅙ",
    "ㅚ",
    "ㅛ",
    "ㅜ",
    "ㅝ",
    "ㅞ",
    "ㅟ",
    "ㅠ",
    "ㅡ",
    "ㅢ",
    "ㅣ",
]
# 종성 리스트. 00 ~ 27 + 1(1개 없음)
JONGSUNG_LIST = [
    " ",
    "ㄱ",
    "ㄲ",
    "ㄳ",
    "ㄴ",
    "ㄵ",
    "ㄶ",
    "ㄷ",
    "ㄹ",
    "ㄺ",
    "ㄻ",
    "ㄼ",
    "ㄽ",
    "ㄾ",
    "ㄿ",
    "ㅀ",
    "ㅁ",
    "ㅂ",
    "ㅄ",
    "ㅅ",
    "ㅆ",
    "ㅇ",
    "ㅈ",
    "ㅊ",
    "ㅋ",
    "ㅌ",
    "ㅍ",
    "ㅎ",
]

options = dict(
    # general setting
    seed=1234,
    batch_size=128,
    workers=4,
    num_epochs=100,
    train_dir="/home/heonsong/Disk2/Dataset/PHD08/phd08_512_split/train",
    val_dir="/home/heonsong/Disk2/Dataset/PHD08/phd08_512_split/val",
    test_dir="/home/heonsong/Disk2/Dataset/PHD08/phd08_2350_split/test",
    # model setting
    name="Normal_512",
    mode="Normal",  # Normal, IR, or LR
    hidden_dim=512,
    addition_dim=128,
    context_dim=len(CHOSUNG_LIST) + len(JUNGSUNG_LIST) + len(JONGSUNG_LIST),
    # optimizer setting
    learning_rate=1e-4,
    weight_decay=0,
    # loss setting
    cat_rate=1.0,
    recon_rate=1.0,
    latent_rate=1.0,
    lr_cat__rate=1e-3,
    lr_latent_rate=1e-3,
)
